services:
- type: web
  name: mi-back-end
  runtime: node
  repo: https://github.com/vpeinado263/mi-back-end
  plan: free
  envVars:
  - key: SECRET_KEY
    sync: false
  - key: PORT
    sync: false
    sync: false
  region: oregon
  buildCommand: npm install && tsc
  startCommand: node build/app.js
version: "1"
